# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a840260bd8fced9c07acb7465b361c4a9360d98e4cd7e584f0c09c0c5e6133b5c1e5155a2a8119db3a4605c5bfe27ed2174e4f986e71bde8af09217e956704fc

test:
  secret_key_base: 16f8ae62cbad814e0f1fb24afc9e77ff9d7da9f183bdc22c0f525b1ddcb9cf98485fe50184a19de495ef85a41262346a40480c64793739ef95c75f7c57a51a25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
